# This is a basic workflow to help you get started with Actions

name: Build NTTB Tournament Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    environment: nttb-ranglijsten
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - run: npm ci
      - run: npm run build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: nttb-tournament-web
          path: public/*
      - run: node ./scripts/correction-for-nttb-ranglijsten.js
      - uses: sand4rt/ftp-deployer@v1.3
        with:
          host: nttb-ranglijsten.nl
          port: 22
          sftp: true
          username: ${{secrets.SFTP_USERNAME}}
          password: ${{secrets.SFTP_PASSWORD}}
          local_folder: public/
          remote_folder: /var/www/ranglijsten/clubtoernooi/
          cleanup: true
